package interfacesDef;


/**
* com/librarymanagement/interfacesDef/UMinterfaces.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UMinterfaces.idl
* Wednesday, 27 March, 2019 7:19:28 PM EDT
*/

public interface UMinterfaces extends UMinterfacesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UMinterfaces
