package interfacesDef;

/**
* com/librarymanagement/interfacesDef/UMinterfacesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UMinterfaces.idl
* Wednesday, 27 March, 2019 7:19:28 PM EDT
*/

public final class UMinterfacesHolder implements org.omg.CORBA.portable.Streamable
{
  public interfacesDef.UMinterfaces value = null;

  public UMinterfacesHolder ()
  {
  }

  public UMinterfacesHolder (interfacesDef.UMinterfaces initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = interfacesDef.UMinterfacesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    interfacesDef.UMinterfacesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return interfacesDef.UMinterfacesHelper.type ();
  }

}
