package interfacesDef;


/**
* com/librarymanagement/interfacesDef/UMinterfacesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UMinterfaces.idl
* Wednesday, 27 March, 2019 7:19:28 PM EDT
*/

public interface UMinterfacesOperations 
{

  //
  String addItem (String managerID, String itemID, String itemName, int quantity);

  //
  String removeItem (String managerID, String itemID, int quantity);

  //
  String listItemAvailability (String managerID);

  //
  String borrowItem (String userID, String itemID);

  //
  String findItem (String userID, String itemName);

  //
  String returnItem (String userID, String itemID);

  //
  String addToWaitingList (String userID, String itemID);

  //
  String exchangeItem (String userID, String newItemID, String oldItemID);

  //
  void shutdown ();
} // interface UMinterfacesOperations
