package frontend.CorbaServerInterface;


/**
* CorbaServerInterface/CorbaServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServerInterface.idl
* Tuesday, 26 March, 2019 11:45:25 PM EDT
*/

public interface CorbaServerInterface extends CorbaServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaServerInterface
